fastapi 和 unicorn 实现的可热重启bot示例
wechaty/python-wechaty-puppet-itchat pull request #18
Opened 2021-09-29 02:48 UTC by fangjiyuan

fastapi 和 unicorn 实现的可热重启bot示例，可以实现web api定制。

2021-09-29 02:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/python-wechaty-puppet-itchat?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/python-wechaty-puppet-itchat?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/python-wechaty-puppet-itchat?pullRequest=18) it.</sub>

2021-09-29 02:52 UTC, wj-Mcat commented
@fangjiyuan  Please sign cla agreement and make CI green.

2021-09-29 04:11 UTC, lyleshaw requested changes
Thank you for your PR, I have left some comments for it, I hope you can modify according to it to merge this PR～

2021-09-29 04:11 UTC, lyleshaw commented on examples/hotreload_bot.py
> +async def send_report(bot,str,str2,str3):
建议这里将 `str,str2,str3` 换为其他变量名，体现变量的含义

2021-09-29 04:11 UTC, lyleshaw commented on examples/hotreload_bot.py
> +sys.path.append(r'd:/github/python-wechaty-puppet-itchat/')
这三行可以考虑删去，一般默认在当前目录下执行

2021-09-29 04:11 UTC, lyleshaw commented on examples/hotreload_bot.py
> +        return 200
接口返回值建议改为如下格式

```json
{
    'code': 100010,             # error code
    'detail': detail,           # show for user
    'fields': fields,           # show for dev, list
    'success': true             # suc or fail
    'data': data,               # data if success else null, be list or dict
}
```

以符合 RESTful 规范，下同

2021-09-30 02:53 UTC, lyleshaw approved these changes
LGTM

2021-09-30 02:53 UTC, merged

2022-04-20 03:58 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited fangjiyuan to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/jekyll/tree/main/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!